title               : Nawon Lee
description         : >-                               # >- means to ignore newlines until "url:"
                      Class of '24 (Computer Science, Biology) at Williams College

url                 : "https://vyshnav2255.github.io"
repository          : 24nl12/portfolio 

email: nl12@williams.edu
github_user: 24nl12
instagram: _nawon
linkedin: ThisIsVyshnav
dribbble: vyshnav_


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
