title               : Nawon Lee
description         : >-                               # >- means to ignore newlines until "url:"
                      Class of '24 (Biology, Computer Science) at Williams College

url                 : "https://24nl12.github.io"
repository          : 24nl12 

email: nawonlee8@gmail.com
github_user: 24nl12
instagram: _nawon
linkedin: NawonLee


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
